export const ColorPallete = {
    primary: 'var(--primary-color)',
    accent: 'var(--accent-color)',
    dark: 'var(--dark-color)',
    light: 'var(--light-color)',
    success: 'var(--success-color)',
    danger: 'var(--danger-color)',
    info: 'var(--info-color)',
    warning: 'var(--warning-color)',
    primaryShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--primary-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--primary-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--primary-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--primary-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--primary-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--primary-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--primary-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--primary-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--primary-color))',
    },
    primaryTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--accent-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--accent-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--accent-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--accent-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--accent-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--accent-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--accent-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--accent-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--accent-color))',
    },
    accentShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--accent-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--accent-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--accent-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--accent-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--accent-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--accent-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--accent-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--accent-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--accent-color))',
    },
    accentTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--primary-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--primary-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--primary-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--primary-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--primary-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--primary-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--primary-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--primary-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--primary-color))',
    },
    darkShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--dark-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--dark-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--dark-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--dark-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--dark-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--dark-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--dark-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--dark-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--dark-color))',
    },
    darkTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--dark-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--dark-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--dark-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--dark-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--dark-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--dark-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--dark-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--dark-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--dark-color))',
    },
    lightShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--light-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--light-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--light-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--light-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--light-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--light-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--light-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--light-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--light-color))',
    },
    lightTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--light-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--light-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--light-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--light-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--light-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--light-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--light-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--light-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--light-color))',
    },
    dangerShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--danger-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--danger-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--danger-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--danger-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--danger-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--danger-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--danger-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--danger-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--danger-color))',
    },
    dangerTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--danger-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--danger-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--danger-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--danger-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--danger-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--danger-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--danger-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--danger-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--danger-color))',
    },
    successShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--success-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--success-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--success-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--success-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--success-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--success-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--success-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--success-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--success-color))',
    },
    successTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--success-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--success-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--success-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--success-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--success-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--success-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--success-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--success-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--success-color))',
    },
    infoShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--info-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--info-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--info-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--info-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--info-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--info-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--info-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--info-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--info-color))',
    },
    infoTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--info-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--info-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--info-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--info-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--info-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--info-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--info-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--info-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--info-color))',
    },
    warningShades: {
        shade10: 'color-mix(in srgb, black 10%, var(--warning-color))',
        shade20: 'color-mix(in srgb, black 20%, var(--warning-color))',
        shade30: 'color-mix(in srgb, black 30%, var(--warning-color))',
        shade40: 'color-mix(in srgb, black 40%, var(--warning-color))',
        shade50: 'color-mix(in srgb, black 50%, var(--warning-color))',
        shade60: 'color-mix(in srgb, black 60%, var(--warning-color))',
        shade70: 'color-mix(in srgb, black 70%, var(--warning-color))',
        shade80: 'color-mix(in srgb, black 80%, var(--warning-color))',
        shade90: 'color-mix(in srgb, black 90%, var(--warning-color))',
    },
    warningTint: {
        tint10: 'color-mix(in srgb, white 10%, var(--warning-color))',
        tint20: 'color-mix(in srgb, white 20%, var(--warning-color))',
        tint30: 'color-mix(in srgb, white 30%, var(--warning-color))',
        tint40: 'color-mix(in srgb, white 40%, var(--warning-color))',
        tint50: 'color-mix(in srgb, white 50%, var(--warning-color))',
        tint60: 'color-mix(in srgb, white 60%, var(--warning-color))',
        tint70: 'color-mix(in srgb, white 70%, var(--warning-color))',
        tint80: 'color-mix(in srgb, white 80%, var(--warning-color))',
        tint90: 'color-mix(in srgb, white 90%, var(--warning-color))',
    },
}